"""update business model

Revision ID: 0d794d877459
Revises: c5ad0a159892
Create Date: 2026-08-07 23:34:09.891562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d794d877459'
down_revision: Union[str, Sequence[str], None] = 'c5ad0a159892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('businesses', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('businesses', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('businesses', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('businesses', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('businesses', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('businesses', sa.Column('logo', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('gst_number', sa.String(length=20), nullable=True))
    op.add_column('businesses', sa.Column('business_registration_number', sa.String(length=50), nullable=True))
    op.add_column('businesses', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('businesses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('businesses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('businesses', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'businesses', ['email'])
    op.drop_constraint(op.f('businesses_user_id_fkey'), 'businesses', type_='foreignkey')
    op.create_foreign_key(None, 'businesses', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('businesses', 'user_id')
    op.alter_column('products', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('products_business_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_business_id_fkey'), 'products', 'businesses', ['business_id'], ['id'])
    op.alter_column('products', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('businesses', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.create_foreign_key(op.f('businesses_user_id_fkey'), 'businesses', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'businesses', type_='unique')
    op.alter_column('businesses', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('businesses', 'updated_at')
    op.drop_column('businesses', 'created_at')
    op.drop_column('businesses', 'is_active')
    op.drop_column('businesses', 'business_registration_number')
    op.drop_column('businesses', 'gst_number')
    op.drop_column('businesses', 'logo')
    op.drop_column('businesses', 'pincode')
    op.drop_column('businesses', 'country')
    op.drop_column('businesses', 'state')
    op.drop_column('businesses', 'city')
    op.drop_column('businesses', 'website')
    op.drop_column('businesses', 'email')
    op.drop_column('businesses', 'owner_id')
    # ### end Alembic commands ###
