"""expand product fields

Revision ID: 72d58e73d3ac
Revises: 69b3a6becf55
Create Date: 2026-08-13 11:52:03.712295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d58e73d3ac'
down_revision: Union[str, Sequence[str], None] = '69b3a6becf55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('sku', sa.String(length=50), nullable=False))
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
